[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "numericalodespy"
version = "0.1"
description = "Python part of numericalodes"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
exclude = ["dev"]
namespaces = false
